run:
  timeout: 2m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - typecheck
    - revive
    - gofmt
    - goimports

issues:
  exclude-use-default: false
