version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  liquibase:
    build:
      context: ./docker/liquibase
    container_name: liquibase
    depends_on:
      - db
    env_file:
      - .env
    environment:
      LIQUIBASE_URL: jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DB}
      LIQUIBASE_USERNAME: ${POSTGRES_USER}
      LIQUIBASE_PASSWORD: ${POSTGRES_PASSWORD}
      LIQUIBASE_CHANGELOG_FILE: ${LIQUIBASE_CHANGELOG_FILE}
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend
    command: >
      liquibase update

  api:
    build:
      context: ./docker/api
    container_name: api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
