version: '3.9'

services:
  api:
    build:
      context: ../../../api
      dockerfile: local/api/Dockerfile
    env_file:
      - ../../../.env
    ports:
      - "8080:8080"
    networks:
      - trainingLog-net

networks:
  trainingLog-net:
    driver: bridge
