version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: s9X#7vP2wQz!F4mL
      POSTGRES_DB: trainingLog
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  liquibase:
    image: liquibase/liquibase
    depends_on:
      - postgres
    volumes:
      - ../../../migrations:/liquibase
    entrypoint: ["liquibase"]
    command:
      - "--url=jdbc:postgresql://postgres:5432/trainingLog"
      - "--username=admin"
      - "--password=s9X#7vP2wQz!F4mL"
      - "--changeLogFile=/liquibase/changelog.yml"
      - "update"
    networks:
      - trainingLog-net

  api:
    build:
      context: ../../../api
      dockerfile: local/api/Dockerfile
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=trainingLog
      - DATABASE_USER=admin
      - DATABASE_PASSWD=admin123
    ports:
      - "8080:8080"
    networks:
      - trainingLog-net

volumes:
  postgres-data:

networks:
  trainingLog-net:
    driver: bridge
